AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Gorkin
Resources:
  getFolders:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/getfolders
      Runtime: go1.x
      Environment:
        Variables:
          BUCKET_NAME: gorkin-features-dev
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /folders
            Method: get
  getFiles:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/getfiles
      Runtime: go1.x
      Environment:
        Variables:
          BUCKET_NAME: gorkin-features-dev
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /files
            Method: get